name: CI/CD

env:
  BUILD_NUMBER: ${{ github.run_number }} 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} ##exports the aws credentials into the environment of the runner.
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
on: 
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  Image_Build:
    name: Build app image
    runs-on: ubuntu-22.04
    env: 
      repository_name: ecomm-php-app
      repository_user: saduasar
      #DOCKERHUB_USERNAME: saduasar
    steps: 
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build image    
        run: |
          docker build -t ${{ env.repository_user }}/${{ env.repository_name }}:${{ env.BUILD_NUMBER }} .
          
      - name: Check app image
        run: |
          docker images

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.repository_user }}/${{ env.repository_name }}:${{ env.BUILD_NUMBER }}'
          format: 'table'
          exit-code: '0' #use 1 when specified vulnerabilities are found
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          
      - name: Deploy app to cluster
        uses: wahyd4/kubectl-helm-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: |
            helm install ecommapp ecommapp-charts 
